/**
 * Minecraft-style splash lines shown by the guide faces. Flavor, not curriculum —
 * jokes, language facts, study/life advice, gentle sarcasm, easter eggs.
 * Any French inside is kept simple and correct, but these are UI text, not lessons.
 */
export const SPLASHES: string[] = [
  `Five minutes a day beats three hours once a month.`,
  `Say it out loud. Your mouth needs the reps too.`,
  `Review the words you got wrong; that's where the gold is.`,
  `You don't have to be fluent today, just less rusty than yesterday.`,
  `Cover the English, guess, then peek. That's the whole trick.`,
  `Sleep on it. Your brain files vocabulary overnight.`,
  `Mistakes are just data. Collect them.`,
  `Read it, hear it, say it, write it. Pick at least two.`,
  `Consistency is a cheat code.`,
  `The hardest part was opening the app. You already did that.`,
  `You're closer than you were five minutes ago.`,
  `Every fluent speaker was once exactly where you are.`,
  `Small steps still go uphill.`,
  `Future-you will be so smug at the DELF.`,
  `Bilingual is just monolingual that didn't quit.`,
  `One more card. You've got one more card in you.`,
  `Progress isn't loud. Keep going anyway.`,
  `"Courage" is a French word. Use it.`,
  `You vs. the subjunctive. You win eventually.`,
  `The streak doesn't care about yesterday. Just show up today.`,
  `About 300 million people speak French worldwide.`,
  `French is spoken on all five inhabited continents.`,
  `Roughly a third of English words have French roots. Merci, 1066.`,
  `French was the language of the English court for nearly 300 years.`,
  `The Académie française has guarded French grammar since 1635.`,
  `French is an official language of the UN, the EU, and the Olympics.`,
  `Most French speakers today live in Africa, not France.`,
  `French was the global language of diplomacy until about WWI.`,
  `Every French noun is masculine or feminine. No neutral ground.`,
  `"Bonjour" literally means "good day."`,
  `"Salut" means both hello and goodbye. Efficient.`,
  `The little hook under ç is called a cédille.`,
  `80 in French is "quatre-vingts" — literally four twenties.`,
  `90 is "quatre-vingt-dix": four-twenties-ten. France commits to the bit.`,
  `In Belgium and Switzerland, 70 is "septante." Lucky them.`,
  `The Eiffel Tower grows about 15 cm taller in summer.`,
  `You already speak French: café, déjà vu, cliché, souvenir.`,
  `French is official in around 30 countries.`,
  `France makes over 1,000 kinds of cheese.`,
  `The metric system was a French Revolution invention.`,
  `Louis XIV reigned 72 years, the longest of any major European monarch.`,
  `"Restaurant," "menu," "chef," "à la carte" — all borrowed from French.`,
  `French added a verb for French-kissing, "galocher," to the dictionary in 2014.`,
  `The accent on "à" (to) vs "a" (has) changes the whole word.`,
  `The -ent on "ils parlent" is silent. Always. Make peace with it.`,
  `Genders aren't logical. Memorise the article with the word.`,
  `tu for friends, vous for everyone you'd be polite to. Unsure? vous.`,
  `Liaison: silent letters wake up before a vowel.`,
  `"on" technically means "one" but really means "we."`,
  `For age, French uses avoir: "j'ai treize ans," never "je suis."`,
  `Negation is a sandwich: ne … pas around the verb.`,
  `é, è and e all sound different. Accents aren't decoration.`,
  `Most French adjectives come after the noun. Most.`,
  `"n'" is just "ne" dressed up for a vowel.`,
  `French questions, easy mode: just raise your voice. "Ça va ?"`,
  `Plurals are often silent: "les chats" barely differs from "le chat."`,
  `"qu'est-ce que" looks terrifying and just means "what."`,
  `French snails are strictly slow food.`,
  `I'd tell a chemistry joke in French, but I'd get no reaction.`,
  `A croissant walked into a café. Too flaky to serve.`,
  `French verbs have moods. Honestly, relatable.`,
  `How many silent letters in French? Most of them, apparently.`,
  `Un, deux, trois… and then the cat sank.`,
  `My French is so rusty it qualifies as a historic monument.`,
  `I'm not arguing, I'm conjugating loudly.`,
  `Oh, skipped the audio again? Bold.`,
  `The subjunctive can smell fear.`,
  `Sure, you "know" it. Flip the card.`,
  `Guessing counts as studying. Probably.`,
  `You and "quatre-vingt-dix" need to have a talk.`,
  `Look at you, doing the hard thing voluntarily.`,
  `Plot twist: it was feminine all along.`,
  `That accent matters more than you'd like.`,
  `Drink some water. Conjugate later.`,
  `Stretch. Even your wrists are learning French.`,
  `Take the break before you need it.`,
  `Comparison is the thief of fluency. Run your own race.`,
  `Done beats perfect, especially in writing tasks.`,
  `Name three objects in your room in French. Right now. The chair won't mind.`,
  `Talk to yourself in French. It's immersion, not weirdness.`,
  `Close the app and speak to a real human eventually. Worth it.`,
  `Whisper the words on the bus. People will respect the dedication.`,
  `Re-reading isn't studying. Testing yourself is.`,
  `If it were easy, it wouldn't come with a certificate.`,
  `Flashcards forgive. They just bring the word back later.`,
  `There are 100 of these. You found one.`,
  `The faces are watching your progress. Approvingly. Mostly.`,
  `Yes, the people on the cards are a little uncanny. They mean well.`,
  `This message will probably change. The one on the home page rarely does.`,
  `Florine: cheaper than a tutor, weirder than a textbook.`,
  `Built with too much coffee and just enough panic.`,
  `Three genders would have been worse. Be grateful for two.`,
  `The "h" is there. It's just never invited to speak.`,
  `Pas mal! (That's French for "I'll allow it.")`,
  `Masculine wins in a mixed group. Blame history, not us.`,
  `Quebec guards French so fiercely it has a government office for it.`,
  `"Week-end," "parking," "shopping" — French borrowed them right back.`,
  `Whisper "je ne sais quoi" and instantly feel 12% more sophisticated.`,
  `Learning a language literally rewires your brain. Feel fancy.`,
  `Bonne chance. (You won't need it, but still.)`,
];
